/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import RNWebdav from 'react-native-webdav';
import RNFS from 'react-native-fs';
export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {
    RNWebdav.sampleMethod('Testing', 123, (message: any) => {
      this.setState({
        status: 'native callback received',
        message,
      });
    });

    // RNWebdav.list(
    //   '2237026218@qq.com',
    //   '********************',
    //   'https://dav.jianguoyun.com/dav/KoodoReader/',
    // )
    //   .then(res => {
    //     console.log(res);
    //   })
    //   .catch(err => {
    //     console.log(err);
    //   });
    RNWebdav.list(
      '2237026218@qq.com',
      '********************',
      'https://dav.jianguoyun.com/dav/',
    )
      .then(res => {
        console.log(res);
      })
      .catch(err => {
        console.log(err);
      });
    // RNWebdav.createDirectory(
    //   '2237026218@qq.com',
    //   '********************',
    //   'https://dav.jianguoyun.com/dav/KoodoReader1/',
    // )
    //   .then(res => {
    //     console.log(res);
    //   })
    //   .catch(err => {
    //     console.log(err);
    //   });

    // RNWebdav.download(
    //   '2237026218@qq.com',
    //   '********************',
    //   'https://dav.jianguoyun.com/dav/KoodoReader/2021-02-12.zip',
    //   RNFS.DocumentDirectoryPath + 'data.zip',
    // )
    //   .then(res => {
    //     console.log(res);
    //   })
    //   .catch(err => {
    //     console.log(err);
    //   });

    // RNWebdav.upload(
    //   '2237026218@qq.com',
    //   '********************',
    //   'https://dav.jianguoyun.com/dav/KoodoReader/data1.zip',
    //   RNFS.DocumentDirectoryPath + 'data.zip',
    //   'application/zip',
    // )
    //   .then(res => {
    //     console.log(res);
    //   })
    //   .catch(err => {
    //     console.log(err);
    //   });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆RNWebdav example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
